const CONSTANTES ={
    URLAPI:'http://eduisictest.pythonanywhere.com/',
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    LOGOUT:'LOGOUT',

    SIGN_UP_REQUEST:'SIGN_UP_REQUEST',


    GET_PROFILE_REQUEST:'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS:'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILED:'GET_PROFILE_FAILED',

    GET_ACCOUNTS_DEBIT_REQUEST:'GET_ACCOUNTS_DEBIT_REQUEST',
    GET_ACCOUNTS_DEBIT_SUCCESS:'GET_ACCOUNTS_DEBIT_SUCCESS',
    GET_ACCOUNTS_DEBIT_FAILED:'GET_ACCOUNTS_DEBIT_FAILED',

    CREATE_ACCOUNT_DEBIT_REQUEST:'CREATE_ACCOUNT_DEBIT_REQUEST',
    CREATE_ACCOUNT_DEBIT_SUCCESS:'CREATE_ACCOUNT_DEBIT_SUCCESS',
    CREATE_ACCOUNT_DEBIT_FAILED:'CREATE_ACCOUNT_DEBIT_FAILED',

    UPDATE_ACCOUNT_DEBIT:'UPDATE_ACCOUNT_DEBIT',



    GET_ACCOUNTS_CREDIT_REQUEST:'GET_ACCOUNTS_CREDIT_REQUEST',
    GET_ACCOUNTS_CREDIT_SUCCESS:'GET_ACCOUNTS_CREDIT_SUCCESS',
    GET_ACCOUNTS_CREDIT_FAILED:'GET_ACCOUNTS_CREDIT_FAILED',

    CREATE_ACCOUNT_CREDIT_REQUEST:'CREATE_ACCOUNT_CREDIT_REQUEST',
    CREATE_ACCOUNT_CREDIT_SUCCESS:'CREATE_ACCOUNT_CREDIT_SUCCESS',
    CREATE_ACCOUNT_CREDIT_FAILED:'CREATE_ACCOUNT_CREDIT_FAILED',

    GET_TYPE_ACCOUNTS_REQUEST:'GET_TYPE_ACCOUNTS_REQUEST',
    GET_TYPE_ACCOUNTS_SUCCESS:'GET_TYPE_ACCOUNTS_SUCCESS',
    GET_TYPE_ACCOUNTS_FAILED:'GET_TYPE_ACCOUNTS_FAILED',


    GET_DETAIL_ACCOUNT_REQUEST:'GET_DETAIL_ACCOUNT_REQUEST',
    GET_DETAIL_ACCOUNT_SUCCESS:'GET_DETAIL_ACCOUNT_SUCCESS',
    GET_DETAIL_ACCOUNT_FAILED:'GET_DETAIL_ACCOUNT_FAILED',



    DEPOSITO_REQUEST:'DEPOSITO_REQUEST',
    DEPOSITO_SUCCESS:'DEPOSITO_SUCCESS',
    DEPOSITO_FAILED:'DEPOSITO_FAILED',

    RETIRO_REQUEST:'RETIRO_REQUEST',
    RETIRO_SUCCESS:'RETIRO_SUCCESS',
    RETIRO_FAILED:'RETIRO_FAILED',

    TRANSACTIONS_REQUEST:'TRANSACTIONS_REQUEST',
    TRANSACTIONS_SUCCESS:'TRANSACTIONS_SUCCESS',
    TRANSACTIONS_FAILED:'TRANSACTIONS_FAILED'
}

export default CONSTANTES
