const CONSTANTES ={
    URLAPI:'http://127.0.0.1:8000',
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    LOGOUT:'LOGOUT',


    GET_PROFILE_REQUEST:'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS:'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILED:'GET_PROFILE_FAILED',


    GET_ACCOUNTS_REQUEST:'GET_ACCOUNTS_REQUEST'


}

export default CONSTANTES
