const CONSTANTES ={
    URLAPI:'http://127.0.0.1:8000',
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',
    LOGOUT:'LOGOUT',


    GET_PROFILE_REQUEST:'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS:'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILED:'GET_PROFILE_FAILED',


    GET_ACCOUNTS_DEBIT_REQUEST:'GET_ACCOUNTS_DEBIT_REQUEST',
    GET_ACCOUNTS_DEBIT_SUCCESS:'GET_ACCOUNTS_DEBIT_SUCCESS',
    GET_ACCOUNTS_DEBIT_FAILED:'GET_ACCOUNTS_DEBIT_FAILED',

    CREATE_ACCOUNT_DEBIT_REQUEST:'CREATE_ACCOUNT_DEBIT_REQUEST',
    CREATE_ACCOUNT_DEBIT_SUCCESS:'CREATE_ACCOUNT_DEBIT_SUCCESS',
    CREATE_ACCOUNT_DEBIT_FAILED:'CREATE_ACCOUNT_DEBIT_FAILED',


    GET_ACCOUNTS_CREDIT_REQUEST:'GET_ACCOUNTS_CREDIT_REQUEST',
    GET_ACCOUNTS_CREDIT_SUCCESS:'GET_ACCOUNTS_CREDIT_SUCCESS',
    GET_ACCOUNTS_CREDIT_FAILED:'GET_ACCOUNTS_CREDIT_FAILED',

    GET_TYPE_ACCOUNTS_REQUEST:'GET_TYPE_ACCOUNTS_REQUEST',
    GET_TYPE_ACCOUNTS_SUCCESS:'GET_TYPE_ACCOUNTS_SUCCESS',
    GET_TYPE_ACCOUNTS_FAILED:'GET_TYPE_ACCOUNTS_FAILED',



}

export default CONSTANTES
